# -*- coding: utf-8 -*-
"""Placementpredict.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kNgTzqpM_S2D31DzyGnPjs0goZkNb6dI
"""

import numpy as np
import pandas as pd

df = pd.read_csv('/content/placement.csv')
df.head()

df.iloc[:,1:]

import matplotlib.pyplot as plt
plt.scatter(df['cgpa'],df['iq'],c = df['placement'])

X = df.iloc[:,0:2]
Y = df.iloc[:,-1]

X

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size = 0.1)

x_train

y_train

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(x_train)
X_train

X_test = scaler.transform(x_test)
X_test

from sklearn.linear_model import LogisticRegression
clf = LogisticRegression()

clf.fit(X_train,y_train)
  y_pred = clf.predict(X_test)

from sklearn.metrics import accuracy_score
 accuracy_score(y_test,y_pred)

from mlxtend.plotting import plot_decision_regions
plot_decision_regions(X_train, y_train.values,
                                clf=clf, legend=2)